export const SituacaoPedidoButtonLabelMap: Record<string, string> = {
  "aprovacao-de-pagamento": "Recusar pagamento,Aprovar pagamento",
  "pagamento-recusado": "-",
  "pendente-de-envio": "Realizar envio",
  "em-transito": "Confirmar recebimento",
  "pedido-cancelado": "-",
  "pedido-nao-entregue": "Realizar novo envio",
  "pedido-recebido": "-",
  "pedido-finalizado": "-",
  "solicitacao-de-troca": "Recusar troca,Aprovar troca",
  "troca-aprovada": "Confirmar recebimento troca",
  "troca-recebida": "Descartar,Adicionar ao estoque",
  "troca-recusada": "-",
  "troca-finalizada": "-",
  "devolucao-solicitada": "Recusar devolução,Aprovar devolução",
  "devolucao-aprovada": "Confirmar recebimento devolução",
  "devolucao-recusada": "-",
  "devolucao-recebida": "Descartar,Adicionar ao estoque",
  "devolucao-finalizada": "-",
};

export const SituacaoPedidoButtonUserLabelMap: Record<string, string> = {
  "aprovacao-de-pagamento": "Cancelar pedido",
  "pagamento-recusado": "-",
  "pendente-de-envio": "Cancelar pedido",
  "em-transito": "Confirmar recebimento",
  "pedido-cancelado": "-",
  "pedido-nao-entregue": "-",
  "pedido-recebido": "Solicitar troca,Solicitar devolução,Finalizar pedido",
  "pedido-finalizado": "-",
  "solicitacao-de-troca": "-",
  "troca-aprovada": "-",
  "troca-recebida": "-",
  "troca-recusada": "-",
  "troca-finalizada": "-",
  "devolucao-solicitada": "-",
  "devolucao-aprovada": "-",
  "devolucao-recusada": "-",
  "devolucao-recebida": "-",
  "devolucao-finalizada": "-",
};
