import { EnderecoType } from "@/concepts/cadastro/EnderecoResidencial/contexts/EnderecoResidencialContext/types";
import { ValidationResult } from "@/utils/validate-schema";
import { Dispatch, SetStateAction } from "react";

export type EnderecoCobrancaContextType = {
  cep: string;
  setCep: Dispatch<SetStateAction<string>>;
  city: string;
  setCity: Dispatch<SetStateAction<string>>;
  country: string;
  setCounty: Dispatch<SetStateAction<string>>;
  logradouro: string;
  setLogradouro: Dispatch<SetStateAction<string>>;
  tipoLogradouro: string;
  setTipoLogradouro: Dispatch<SetStateAction<string>>;
  neighborhood: string;
  setNeighborhood: Dispatch<SetStateAction<string>>;
  number: string;
  setNumber: Dispatch<SetStateAction<string>>;
  observations: string;
  setObservations: Dispatch<SetStateAction<string>>;
  residenceType: string;
  setResidenceType: Dispatch<SetStateAction<string>>;
  state: string;
  setState: Dispatch<SetStateAction<string>>;
  shortPhrase: string;
  setShortPhrase: Dispatch<SetStateAction<string>>;
  enderecos: EnderecoType[];
  setEnderecos: Dispatch<SetStateAction<EnderecoType[]>>;
  isCadastrando: boolean;
  setIsCadastrando: Dispatch<SetStateAction<boolean>>;
  isEditando: boolean;
  setIsEditando: Dispatch<SetStateAction<boolean>>;
  fillForm: (data: EnderecoType) => void;
  clearForm: () => void;
  errors: ValidationResult[];
  setErrors: Dispatch<SetStateAction<ValidationResult[]>>;
};
